# Generated by Django 5.0.2 on 2024-04-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("argus_incident", "0007_alter_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndpointEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("description", models.TextField()),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoint_events",
                        to="argus_incident.incident",
                    ),
                ),
            ],
        ),
    ]
